// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SecurityRule.E2E.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Управление группами")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class УправлениеГруппамиFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru"), "Features", "Управление группами", "  Как администратор системы\n  Я хочу управлять группами пользователей\n  Чтобы орг" +
                "анизовывать учётные записи по структуре", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Группы.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Группы.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Просмотр страницы со списком групп")]
        public async global::System.Threading.Tasks.Task ПросмотрСтраницыСоСпискомГрупп()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Просмотр страницы со списком групп", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.WhenAsync("я перехожу на страницу групп", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 9
    await testRunner.ThenAsync("я вижу заголовок \"Группы\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Добавление новой группы")]
        public async global::System.Threading.Tasks.Task ДобавлениеНовойГруппы()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Добавление новой группы", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
    await testRunner.WhenAsync("я перехожу на страницу добавления группы", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 13
    await testRunner.AndAsync("я заполняю поле \"Название\" значением \"DevTeam\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 14
    await testRunner.AndAsync("я нажимаю кнопку \"Сохранить\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 15
    await testRunner.ThenAsync("я нахожусь на странице \"/groups\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
#line 16
    await testRunner.AndAsync("я вижу текст \"DevTeam\" на странице", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Просмотр деталей группы")]
        public async global::System.Threading.Tasks.Task ПросмотрДеталейГруппы()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Просмотр деталей группы", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("в системе существует группа с именем \"OpsTeam\" и описанием \"Операционная команда\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 20
    await testRunner.WhenAsync("я открываю страницу деталей группы \"OpsTeam\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 21
    await testRunner.ThenAsync("я вижу текст \"OpsTeam\" на странице", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
#line 22
    await testRunner.AndAsync("я вижу текст \"Операционная команда\" на странице", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Редактирование группы")]
        public async global::System.Threading.Tasks.Task РедактированиеГруппы()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Редактирование группы", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("в системе существует группа с именем \"OldGroup\" и описанием \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 26
    await testRunner.WhenAsync("я открываю страницу редактирования группы \"OldGroup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 27
    await testRunner.AndAsync("я заменяю значение поля \"Название\" на \"UpdatedGroup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 28
    await testRunner.AndAsync("я нажимаю кнопку \"Сохранить\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 29
    await testRunner.ThenAsync("я вижу текст \"UpdatedGroup\" на странице", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Удаление группы")]
        public async global::System.Threading.Tasks.Task УдалениеГруппы()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Удаление группы", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
    await testRunner.GivenAsync("в системе существует группа с именем \"TempGroup\" и описанием \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 33
    await testRunner.WhenAsync("я открываю страницу редактирования группы \"TempGroup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 34
    await testRunner.AndAsync("я нажимаю кнопку \"Удалить\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 35
    await testRunner.ThenAsync("я нахожусь на странице \"/groups\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
#line 36
    await testRunner.AndAsync("на странице нет текста \"TempGroup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Добавление дочерней группы при редактировании")]
        public async global::System.Threading.Tasks.Task ДобавлениеДочернейГруппыПриРедактировании()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Добавление дочерней группы при редактировании", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("в системе существует группа с именем \"ParentGroup\" и описанием \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 40
    await testRunner.AndAsync("в системе существует группа с именем \"ChildGroup\" и описанием \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 41
    await testRunner.WhenAsync("я открываю страницу редактирования группы \"ParentGroup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 42
    await testRunner.ThenAsync("я вижу заголовок \"Редактировать группу\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Группа может входить в другую группу (родительская группа)")]
        public async global::System.Threading.Tasks.Task ГруппаМожетВходитьВДругуюГруппуРодительскаяГруппа()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Группа может входить в другую группу (родительская группа)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("в системе существует группа с именем \"TopLevel\" и описанием \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 46
    await testRunner.AndAsync("в системе существует группа с именем \"SubGroup\" и описанием \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 47
    await testRunner.WhenAsync("я открываю страницу редактирования группы \"SubGroup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 48
    await testRunner.ThenAsync("я вижу заголовок \"Редактировать группу\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
