// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SecurityRule.E2E.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Полнотекстовый поиск")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ПолнотекстовыйПоискFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("ru"), "Features", "Полнотекстовый поиск", "  Как администратор системы\n  Я хочу искать записи по всем полям\n  Чтобы быстро н" +
                "аходить нужную информацию", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Поиск.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Поиск.feature.ndjson", 11);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Строка поиска отображается на всех страницах")]
        public async global::System.Threading.Tasks.Task СтрокаПоискаОтображаетсяНаВсехСтраницах()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Строка поиска отображается на всех страницах", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.WhenAsync("я перехожу на страницу серверов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 9
    await testRunner.ThenAsync("я вижу поле поиска в шапке", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Поиск сервера по названию")]
        public async global::System.Threading.Tasks.Task ПоискСервераПоНазванию()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поиск сервера по названию", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
    await testRunner.GivenAsync("в системе существует сервер Name \"SearchServer-Alpha\" IP \"10.10.10.1\" OS \"Ubuntu " +
                        "22.04\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 13
    await testRunner.WhenAsync("я перехожу на страницу серверов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 14
    await testRunner.AndAsync("я ввожу в поле поиска текст \"SearchServer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 15
    await testRunner.ThenAsync("в результатах поиска я вижу \"SearchServer-Alpha\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
#line 16
    await testRunner.AndAsync("в результатах поиска найденный текст \"SearchServer\" выделен", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Поиск сервера по IP адресу")]
        public async global::System.Threading.Tasks.Task ПоискСервераПоIPАдресу()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поиск сервера по IP адресу", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("в системе существует сервер Name \"IPServer\" IP \"192.168.99.1\" OS \"CentOS\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 20
    await testRunner.WhenAsync("я перехожу на страницу серверов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 21
    await testRunner.AndAsync("я ввожу в поле поиска текст \"192.168.99\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 22
    await testRunner.ThenAsync("в результатах поиска я вижу \"192.168.99.1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Поиск по несуществующему тексту показывает «Ничего не найдено»")]
        public async global::System.Threading.Tasks.Task ПоискПоНесуществующемуТекстуПоказываетНичегоНеНайдено()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поиск по несуществующему тексту показывает «Ничего не найдено»", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.WhenAsync("я перехожу на страницу серверов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 26
    await testRunner.AndAsync("я ввожу в поле поиска текст \"ZZZZNOTEXISTS999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 27
    await testRunner.ThenAsync("в результатах поиска я вижу \"Ничего не найдено\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Клик на результат поиска переходит на страницу деталей")]
        public async global::System.Threading.Tasks.Task КликНаРезультатПоискаПереходитНаСтраницуДеталей()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Клик на результат поиска переходит на страницу деталей", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("в системе существует сервер Name \"ClickableServer\" IP \"10.20.30.40\" OS \"Debian\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 31
    await testRunner.WhenAsync("я перехожу на страницу серверов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 32
    await testRunner.AndAsync("я ввожу в поле поиска текст \"ClickableServer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 33
    await testRunner.AndAsync("я нажимаю на первый результат поиска", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 34
    await testRunner.ThenAsync("URL страницы содержит \"/servers/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Поиск сервиса по AD учётной записи")]
        public async global::System.Threading.Tasks.Task ПоискСервисаПоADУчётнойЗаписи()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поиск сервиса по AD учётной записи", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("в системе существует сервис Name \"AuthService\" UserName \"domain\\johndoe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 38
    await testRunner.WhenAsync("я перехожу на страницу сервисов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 39
    await testRunner.AndAsync("я ввожу в поле поиска текст \"johndoe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 40
    await testRunner.ThenAsync("в результатах поиска я вижу \"domain\\johndoe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Поиск пользователя по названию")]
        public async global::System.Threading.Tasks.Task ПоискПользователяПоНазванию()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поиск пользователя по названию", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
    await testRunner.GivenAsync("в системе существует пользователь Name \"kl\\ermakov\" Description \"Иванов Иван\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 44
    await testRunner.WhenAsync("я перехожу на страницу пользователей", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 45
    await testRunner.AndAsync("я ввожу в поле поиска текст \"ermakov\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 46
    await testRunner.ThenAsync("в результатах поиска я вижу \"kl\\ermakov\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Поиск группы по названию")]
        public async global::System.Threading.Tasks.Task ПоискГруппыПоНазванию()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поиск группы по названию", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
    await testRunner.GivenAsync("в системе существует группа Name \"Admins\" Description \"Группа администраторов\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 50
    await testRunner.WhenAsync("я перехожу на страницу групп", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 51
    await testRunner.AndAsync("я ввожу в поле поиска текст \"Admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 52
    await testRunner.ThenAsync("в результатах поиска я вижу \"Admins\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Строка поиска короче 2 символов не вызывает поиск")]
        public async global::System.Threading.Tasks.Task СтрокаПоискаКороче2СимволовНеВызываетПоиск()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Строка поиска короче 2 символов не вызывает поиск", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 55
    await testRunner.GivenAsync("в системе существует сервер Name \"ShortQueryServer\" IP \"1.2.3.4\" OS \"FreeBSD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 56
    await testRunner.WhenAsync("я перехожу на страницу серверов", ((string)(null)), ((global::Reqnroll.Table)(null)), "Когда ");
#line hidden
#line 57
    await testRunner.AndAsync("я ввожу в поле поиска текст \"S\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "И ");
#line hidden
#line 58
    await testRunner.ThenAsync("выпадающий список поиска не отображается", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тогда ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
