apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: security-rule
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Authentication__UseActiveDirectory: "false"
  Authentication__DevelopmentUser: "k8s-user"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
