// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityRule.Infrastructure.Data;

#nullable disable

namespace SecurityRule.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527142915_AddPartnerAgeRanges")]
    partial class AddPartnerAgeRanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppServiceCertificate", b =>
                {
                    b.Property<int>("CertificatesId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("CertificatesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ServiceCertificates", (string)null);
                });

            modelBuilder.Entity("AppServicePartnerName", b =>
                {
                    b.Property<int>("PartnersId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("PartnersId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ServicePartnerNames", (string)null);
                });

            modelBuilder.Entity("AppServiceServer", b =>
                {
                    b.Property<int>("ServersId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("ServersId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ServerServices", (string)null);
                });

            modelBuilder.Entity("AppServiceTag", b =>
                {
                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ServicesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ServiceTags", (string)null);
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AgeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("AgeOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Value = 2
                        },
                        new
                        {
                            Id = 4,
                            Value = 3
                        },
                        new
                        {
                            Id = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 6,
                            Value = 5
                        },
                        new
                        {
                            Id = 7,
                            Value = 6
                        },
                        new
                        {
                            Id = 8,
                            Value = 7
                        },
                        new
                        {
                            Id = 9,
                            Value = 8
                        },
                        new
                        {
                            Id = 10,
                            Value = 9
                        },
                        new
                        {
                            Id = 11,
                            Value = 10
                        },
                        new
                        {
                            Id = 12,
                            Value = 11
                        },
                        new
                        {
                            Id = 13,
                            Value = 12
                        },
                        new
                        {
                            Id = 14,
                            Value = 13
                        },
                        new
                        {
                            Id = 15,
                            Value = 14
                        },
                        new
                        {
                            Id = 16,
                            Value = 15
                        },
                        new
                        {
                            Id = 17,
                            Value = 16
                        },
                        new
                        {
                            Id = 18,
                            Value = 17
                        },
                        new
                        {
                            Id = 19,
                            Value = 18
                        },
                        new
                        {
                            Id = 20,
                            Value = 19
                        },
                        new
                        {
                            Id = 21,
                            Value = 20
                        },
                        new
                        {
                            Id = 22,
                            Value = 21
                        },
                        new
                        {
                            Id = 23,
                            Value = 22
                        },
                        new
                        {
                            Id = 24,
                            Value = 23
                        },
                        new
                        {
                            Id = 25,
                            Value = 24
                        },
                        new
                        {
                            Id = 26,
                            Value = 25
                        },
                        new
                        {
                            Id = 27,
                            Value = 26
                        },
                        new
                        {
                            Id = 28,
                            Value = 27
                        },
                        new
                        {
                            Id = 29,
                            Value = 28
                        },
                        new
                        {
                            Id = 30,
                            Value = 29
                        },
                        new
                        {
                            Id = 31,
                            Value = 30
                        },
                        new
                        {
                            Id = 32,
                            Value = 31
                        },
                        new
                        {
                            Id = 33,
                            Value = 32
                        },
                        new
                        {
                            Id = 34,
                            Value = 33
                        },
                        new
                        {
                            Id = 35,
                            Value = 34
                        },
                        new
                        {
                            Id = 36,
                            Value = 35
                        },
                        new
                        {
                            Id = 37,
                            Value = 36
                        },
                        new
                        {
                            Id = 38,
                            Value = 37
                        },
                        new
                        {
                            Id = 39,
                            Value = 38
                        },
                        new
                        {
                            Id = 40,
                            Value = 39
                        },
                        new
                        {
                            Id = 41,
                            Value = 40
                        },
                        new
                        {
                            Id = 42,
                            Value = 41
                        },
                        new
                        {
                            Id = 43,
                            Value = 42
                        },
                        new
                        {
                            Id = 44,
                            Value = 43
                        },
                        new
                        {
                            Id = 45,
                            Value = 44
                        },
                        new
                        {
                            Id = 46,
                            Value = 45
                        },
                        new
                        {
                            Id = 47,
                            Value = 46
                        },
                        new
                        {
                            Id = 48,
                            Value = 47
                        },
                        new
                        {
                            Id = 49,
                            Value = 48
                        },
                        new
                        {
                            Id = 50,
                            Value = 49
                        },
                        new
                        {
                            Id = 51,
                            Value = 50
                        },
                        new
                        {
                            Id = 52,
                            Value = 51
                        },
                        new
                        {
                            Id = 53,
                            Value = 52
                        },
                        new
                        {
                            Id = 54,
                            Value = 53
                        },
                        new
                        {
                            Id = 55,
                            Value = 54
                        },
                        new
                        {
                            Id = 56,
                            Value = 55
                        },
                        new
                        {
                            Id = 57,
                            Value = 56
                        },
                        new
                        {
                            Id = 58,
                            Value = 57
                        },
                        new
                        {
                            Id = 59,
                            Value = 58
                        },
                        new
                        {
                            Id = 60,
                            Value = 59
                        },
                        new
                        {
                            Id = 61,
                            Value = 60
                        },
                        new
                        {
                            Id = 62,
                            Value = 61
                        },
                        new
                        {
                            Id = 63,
                            Value = 62
                        },
                        new
                        {
                            Id = 64,
                            Value = 63
                        },
                        new
                        {
                            Id = 65,
                            Value = 64
                        },
                        new
                        {
                            Id = 66,
                            Value = 65
                        },
                        new
                        {
                            Id = 67,
                            Value = 66
                        },
                        new
                        {
                            Id = 68,
                            Value = 67
                        },
                        new
                        {
                            Id = 69,
                            Value = 68
                        },
                        new
                        {
                            Id = 70,
                            Value = 69
                        },
                        new
                        {
                            Id = 71,
                            Value = 70
                        },
                        new
                        {
                            Id = 72,
                            Value = 71
                        },
                        new
                        {
                            Id = 73,
                            Value = 72
                        },
                        new
                        {
                            Id = 74,
                            Value = 73
                        },
                        new
                        {
                            Id = 75,
                            Value = 74
                        },
                        new
                        {
                            Id = 76,
                            Value = 75
                        },
                        new
                        {
                            Id = 77,
                            Value = 76
                        },
                        new
                        {
                            Id = 78,
                            Value = 77
                        },
                        new
                        {
                            Id = 79,
                            Value = 78
                        },
                        new
                        {
                            Id = 80,
                            Value = 79
                        },
                        new
                        {
                            Id = 81,
                            Value = 80
                        },
                        new
                        {
                            Id = 82,
                            Value = 81
                        },
                        new
                        {
                            Id = 83,
                            Value = 82
                        },
                        new
                        {
                            Id = 84,
                            Value = 83
                        },
                        new
                        {
                            Id = 85,
                            Value = 84
                        },
                        new
                        {
                            Id = 86,
                            Value = 85
                        },
                        new
                        {
                            Id = 87,
                            Value = 86
                        },
                        new
                        {
                            Id = 88,
                            Value = 87
                        },
                        new
                        {
                            Id = 89,
                            Value = 88
                        },
                        new
                        {
                            Id = 90,
                            Value = 89
                        },
                        new
                        {
                            Id = 91,
                            Value = 90
                        },
                        new
                        {
                            Id = 92,
                            Value = 91
                        },
                        new
                        {
                            Id = 93,
                            Value = 92
                        },
                        new
                        {
                            Id = 94,
                            Value = 93
                        },
                        new
                        {
                            Id = 95,
                            Value = 94
                        },
                        new
                        {
                            Id = 96,
                            Value = 95
                        },
                        new
                        {
                            Id = 97,
                            Value = 96
                        },
                        new
                        {
                            Id = 98,
                            Value = 97
                        },
                        new
                        {
                            Id = 99,
                            Value = 98
                        },
                        new
                        {
                            Id = 100,
                            Value = 99
                        },
                        new
                        {
                            Id = 101,
                            Value = 100
                        });
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AppService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppServices");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.OperatingSystemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystemOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Windows 11"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Windows Server 2022"
                        });
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.PartnerAgeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeFrom")
                        .HasColumnType("int");

                    b.Property<int>("AgeTo")
                        .HasColumnType("int");

                    b.Property<int>("AppServiceId")
                        .HasColumnType("int");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppServiceId");

                    b.ToTable("PartnerAgeRanges");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.PartnerName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartnerNames");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.ServiceConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DestinationServerId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SourceServerId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationServerId");

                    b.HasIndex("DestinationServiceId");

                    b.HasIndex("SourceServerId");

                    b.HasIndex("SourceServiceId");

                    b.ToTable("ServiceConnections");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServerTag", b =>
                {
                    b.Property<int>("ServersId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ServersId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ServerTags", (string)null);
                });

            modelBuilder.Entity("AppServiceCertificate", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Certificate", null)
                        .WithMany()
                        .HasForeignKey("CertificatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.AppService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServicePartnerName", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.PartnerName", null)
                        .WithMany()
                        .HasForeignKey("PartnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.AppService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServiceServer", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Server", null)
                        .WithMany()
                        .HasForeignKey("ServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.AppService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServiceTag", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.AppService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AppService", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.User", "User")
                        .WithMany("Services")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.PartnerAgeRange", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.AppService", "AppService")
                        .WithMany("PartnerAgeRanges")
                        .HasForeignKey("AppServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppService");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.ServiceConnection", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Server", "DestinationServer")
                        .WithMany("DestinationConnections")
                        .HasForeignKey("DestinationServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SecurityRule.Domain.Models.AppService", "DestinationService")
                        .WithMany("DestinationConnections")
                        .HasForeignKey("DestinationServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.Server", "SourceServer")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SecurityRule.Domain.Models.AppService", "SourceService")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationServer");

                    b.Navigation("DestinationService");

                    b.Navigation("SourceServer");

                    b.Navigation("SourceService");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.User", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Certificate", "Certificate")
                        .WithMany("Users")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("ServerTag", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Server", null)
                        .WithMany()
                        .HasForeignKey("ServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AppService", b =>
                {
                    b.Navigation("DestinationConnections");

                    b.Navigation("PartnerAgeRanges");

                    b.Navigation("SourceConnections");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Certificate", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Server", b =>
                {
                    b.Navigation("DestinationConnections");

                    b.Navigation("SourceConnections");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.User", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
