// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityRule.Infrastructure.Data;

#nullable disable

namespace SecurityRule.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppServiceCertificate", b =>
                {
                    b.Property<int>("CertificatesId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("CertificatesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ServiceCertificates", (string)null);
                });

            modelBuilder.Entity("AppServiceServer", b =>
                {
                    b.Property<int>("ServersId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("ServersId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ServerServices", (string)null);
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AppService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppServices");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.ServiceConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinationServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationServerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasDefaultValue("")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SourceServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationServiceId");

                    b.HasIndex("DestinationServerId");

                    b.HasIndex("SourceServiceId");

                    b.HasIndex("SourceServerId");

                    b.ToTable("ServiceConnections");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.OperatingSystemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystemOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Windows 11"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Windows Server 2022"
                        });
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.ServiceConnection", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Server", "SourceServer")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SecurityRule.Domain.Models.AppService", "SourceService")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SecurityRule.Domain.Models.Server", "DestinationServer")
                        .WithMany("DestinationConnections")
                        .HasForeignKey("DestinationServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SecurityRule.Domain.Models.AppService", "DestinationService")
                        .WithMany("DestinationConnections")
                        .HasForeignKey("DestinationServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceServer");
                    b.Navigation("SourceService");
                    b.Navigation("DestinationServer");
                    b.Navigation("DestinationService");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AppService", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.User", "User")
                        .WithMany("Services")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppServiceCertificate", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Certificate", null)
                        .WithMany()
                        .HasForeignKey("CertificatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.AppService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppServiceServer", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Server", null)
                        .WithMany()
                        .HasForeignKey("ServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityRule.Domain.Models.AppService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.User", b =>
                {
                    b.HasOne("SecurityRule.Domain.Models.Certificate", "Certificate")
                        .WithMany("Users")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Certificate");
                    b.Navigation("Services");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Server", b =>
                {
                    b.Navigation("SourceConnections");
                    b.Navigation("DestinationConnections");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.AppService", b =>
                {
                    b.Navigation("SourceConnections");
                    b.Navigation("DestinationConnections");
                });

            modelBuilder.Entity("SecurityRule.Domain.Models.Certificate", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
