apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: security-rule
  labels:
    app: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: sa-password
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
